CREATE TABLE `broker_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`firstName` varchar(128),
	`lastName` varchar(128),
	`fullName` varchar(255) NOT NULL,
	`nickname` varchar(64),
	`company` varchar(255),
	`title` varchar(128),
	`department` varchar(128),
	`seniority` enum('c_level','vp','director','manager','associate','analyst','other'),
	`contactType` enum('investor','family_office','fund_manager','broker','advisor','principal','operator','service_provider','other') DEFAULT 'investor',
	`familyOfficeId` int,
	`institutionalInvestorId` int,
	`email` varchar(320),
	`emailSecondary` varchar(320),
	`phone` varchar(32),
	`phoneSecondary` varchar(32),
	`linkedinUrl` varchar(512),
	`twitterHandle` varchar(64),
	`telegramHandle` varchar(64),
	`discordHandle` varchar(64),
	`whatsappNumber` varchar(32),
	`signalNumber` varchar(32),
	`groupChats` json,
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64),
	`timezone` varchar(64),
	`investmentFocus` json,
	`sectorExpertise` json,
	`geographicFocus` json,
	`typicalDealSize` varchar(64),
	`relationshipStrength` enum('cold','warm','hot','close','inner_circle') DEFAULT 'cold',
	`lastContactDate` timestamp,
	`nextFollowUp` timestamp,
	`contactFrequency` enum('daily','weekly','biweekly','monthly','quarterly','yearly','as_needed'),
	`totalDealsDiscussed` int DEFAULT 0,
	`totalDealsClosed` int DEFAULT 0,
	`totalDealValue` decimal(18,2) DEFAULT '0.00',
	`notes` text,
	`tags` json,
	`customFields` json,
	`dataSource` varchar(128),
	`isVerified` boolean DEFAULT false,
	`lastVerified` timestamp,
	`doNotContact` boolean DEFAULT false,
	`preferredContactMethod` enum('email','phone','linkedin','telegram','whatsapp','in_person'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `broker_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contact_interactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactId` int NOT NULL,
	`userId` int NOT NULL,
	`interactionType` enum('email_sent','email_received','call','meeting','video_call','message','linkedin_message','introduction','deal_discussion','other') NOT NULL,
	`subject` varchar(255),
	`summary` text,
	`outcome` varchar(255),
	`dealId` int,
	`intentId` int,
	`scheduledAt` timestamp,
	`completedAt` timestamp,
	`duration` int,
	`requiresFollowUp` boolean DEFAULT false,
	`followUpDate` timestamp,
	`followUpNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contact_interactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deal_flow_sources` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('direct_relationship','referral','platform','conference','cold_outreach','inbound','broker_network','other') NOT NULL,
	`description` text,
	`contactInfo` varchar(255),
	`totalDealsSourced` int DEFAULT 0,
	`totalDealsClosed` int DEFAULT 0,
	`totalDealValue` decimal(18,2) DEFAULT '0.00',
	`conversionRate` decimal(5,2),
	`qualityScore` decimal(5,2),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deal_flow_sources_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `family_offices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255),
	`type` enum('single_family','multi_family','embedded','virtual') DEFAULT 'single_family',
	`foundingFamily` varchar(255),
	`wealthSource` varchar(255),
	`generationWealth` int DEFAULT 1,
	`aum` bigint,
	`aumRange` enum('under_100m','100m_500m','500m_1b','1b_5b','5b_10b','10b_50b','50b_plus'),
	`minimumInvestment` bigint,
	`typicalCheckSize` varchar(64),
	`headquarters` varchar(255),
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64) DEFAULT 'USA',
	`region` enum('north_america','europe','asia','middle_east','latin_america','africa','oceania') DEFAULT 'north_america',
	`investmentFocus` json,
	`sectorPreferences` json,
	`geographicFocus` json,
	`stagePreferences` json,
	`investmentStyle` enum('passive','active','control','co_invest','direct_only','fund_only','hybrid') DEFAULT 'hybrid',
	`holdingPeriod` varchar(64),
	`returnTarget` varchar(64),
	`teamSize` int,
	`hasInHouseCIO` boolean DEFAULT false,
	`hasInHouseLegal` boolean DEFAULT false,
	`usesExternalAdvisors` boolean DEFAULT true,
	`website` varchar(512),
	`linkedinUrl` varchar(512),
	`email` varchar(320),
	`phone` varchar(32),
	`keyContacts` json,
	`dealsPerYear` int,
	`lastKnownDeal` timestamp,
	`totalInvestments` int,
	`dataSource` varchar(128),
	`dataConfidence` enum('low','medium','high','verified') DEFAULT 'medium',
	`lastVerified` timestamp,
	`isActive` boolean DEFAULT true,
	`claimedByUserId` int,
	`relationshipCount` int DEFAULT 0,
	`globalRank` int,
	`regionRank` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `family_offices_id` PRIMARY KEY(`id`),
	CONSTRAINT `family_offices_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `institutional_investors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('pension_fund','endowment','sovereign_wealth','insurance','bank','asset_manager','hedge_fund','private_equity','venture_capital') NOT NULL,
	`aum` bigint,
	`headquarters` varchar(255),
	`country` varchar(64),
	`website` varchar(512),
	`investmentFocus` json,
	`minimumInvestment` bigint,
	`keyContacts` json,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `institutional_investors_id` PRIMARY KEY(`id`)
);
