CREATE TABLE `data_enrichment_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` enum('family_office','contact','company') NOT NULL,
	`entityId` int NOT NULL,
	`provider` varchar(64) NOT NULL,
	`enrichmentType` enum('aum_update','contact_info','investment_activity','news','team_changes','social_profiles','company_info','full_refresh') NOT NULL,
	`status` enum('pending','success','partial','failed') DEFAULT 'pending',
	`previousData` json,
	`newData` json,
	`fieldsUpdated` json,
	`apiResponseCode` int,
	`apiResponseMessage` text,
	`apiCreditsUsed` decimal(10,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_enrichment_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `family_office_targets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`familyOfficeId` int NOT NULL,
	`status` enum('identified','researching','outreach_planned','contacted','in_conversation','meeting_scheduled','proposal_sent','negotiating','converted','declined','on_hold') DEFAULT 'identified',
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`firstContactDate` timestamp,
	`lastContactDate` timestamp,
	`nextFollowUpDate` timestamp,
	`totalTouchpoints` int DEFAULT 0,
	`primaryContactName` varchar(255),
	`primaryContactTitle` varchar(128),
	`primaryContactEmail` varchar(320),
	`primaryContactLinkedIn` varchar(512),
	`primaryContactPhone` varchar(32),
	`estimatedDealSize` decimal(18,2),
	`dealType` enum('co_investment','fund_commitment','direct_deal','advisory','other'),
	`interestedSectors` json,
	`notes` text,
	`lastActivitySummary` text,
	`convertedToRelationshipId` int,
	`convertedToDealId` int,
	`conversionDate` timestamp,
	`fitScore` decimal(5,2),
	`engagementScore` decimal(5,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `family_office_targets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `news_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` enum('family_office','contact','company') NOT NULL,
	`entityId` int NOT NULL,
	`title` varchar(512) NOT NULL,
	`summary` text,
	`content` text,
	`sourceUrl` varchar(1024),
	`sourceName` varchar(128),
	`newsType` enum('investment','exit','fund_raise','team_change','acquisition','partnership','regulatory','market_news','press_release','other') DEFAULT 'other',
	`sentiment` enum('positive','neutral','negative'),
	`relevanceScore` decimal(5,2),
	`imageUrl` text,
	`publishedAt` timestamp,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	`isRead` boolean DEFAULT false,
	`isSaved` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `news_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `social_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` enum('user','contact','family_office') NOT NULL,
	`entityId` int NOT NULL,
	`platform` enum('linkedin','instagram','twitter','facebook','youtube','tiktok','crunchbase','pitchbook','angellist','other') NOT NULL,
	`profileUrl` varchar(512) NOT NULL,
	`username` varchar(128),
	`displayName` varchar(255),
	`profileImageUrl` text,
	`bio` text,
	`followerCount` int,
	`followingCount` int,
	`connectionCount` int,
	`postCount` int,
	`linkedinHeadline` varchar(255),
	`linkedinLocation` varchar(128),
	`linkedinIndustry` varchar(128),
	`linkedinCompany` varchar(255),
	`linkedinTitle` varchar(255),
	`instagramIsVerified` boolean DEFAULT false,
	`instagramIsPrivate` boolean DEFAULT false,
	`instagramCategory` varchar(128),
	`isVerified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`lastSyncedAt` timestamp,
	`syncStatus` enum('pending','synced','failed') DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `social_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `target_activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`targetId` int NOT NULL,
	`userId` int NOT NULL,
	`activityType` enum('email_sent','email_received','call_made','call_received','linkedin_connection','linkedin_message','meeting','video_call','introduction_made','introduction_received','document_shared','proposal_sent','follow_up','note_added','status_change') NOT NULL,
	`subject` varchar(255),
	`description` text,
	`outcome` varchar(255),
	`contactPerson` varchar(255),
	`contactMethod` varchar(64),
	`scheduledAt` timestamp,
	`completedAt` timestamp,
	`duration` int,
	`requiresFollowUp` boolean DEFAULT false,
	`followUpDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `target_activities_id` PRIMARY KEY(`id`)
);
