CREATE TABLE `calendar_connections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`provider` enum('google','outlook','apple') NOT NULL,
	`accessToken` text,
	`refreshToken` text,
	`tokenExpiry` timestamp,
	`calendarId` varchar(255),
	`calendarName` varchar(255),
	`syncEnabled` boolean DEFAULT true,
	`lastSyncAt` timestamp,
	`syncStatus` enum('active','paused','error') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `calendar_connections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `calendar_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`externalId` varchar(255),
	`provider` enum('google','outlook','apple','internal') DEFAULT 'internal',
	`title` varchar(512) NOT NULL,
	`description` text,
	`location` varchar(512),
	`meetingLink` varchar(1024),
	`startTime` timestamp NOT NULL,
	`endTime` timestamp NOT NULL,
	`allDay` boolean DEFAULT false,
	`timezone` varchar(64) DEFAULT 'UTC',
	`isRecurring` boolean DEFAULT false,
	`recurrenceRule` varchar(255),
	`eventType` enum('meeting','call','follow_up','due_diligence','deal_room','pitch','closing','reminder','other') DEFAULT 'meeting',
	`relatedDealId` int,
	`relatedTargetId` int,
	`relatedContactId` int,
	`attendees` json,
	`status` enum('confirmed','tentative','cancelled') DEFAULT 'confirmed',
	`reminders` json,
	`notes` text,
	`outcome` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `calendar_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `conversion_funnels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`stage` varchar(64) NOT NULL,
	`stageOrder` int NOT NULL,
	`totalEntered` int DEFAULT 0,
	`totalExited` int DEFAULT 0,
	`totalConverted` int DEFAULT 0,
	`valueEntered` decimal(18,2) DEFAULT '0.00',
	`valueConverted` decimal(18,2) DEFAULT '0.00',
	`avgTimeInStage` int,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `conversion_funnels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deal_analytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`periodType` enum('daily','weekly','monthly','quarterly','yearly') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalDeals` int DEFAULT 0,
	`newDeals` int DEFAULT 0,
	`closedDeals` int DEFAULT 0,
	`lostDeals` int DEFAULT 0,
	`totalPipelineValue` decimal(18,2) DEFAULT '0.00',
	`closedValue` decimal(18,2) DEFAULT '0.00',
	`lostValue` decimal(18,2) DEFAULT '0.00',
	`conversionRate` decimal(5,2),
	`avgDealCycleTime` int,
	`avgDealSize` decimal(18,2),
	`dealsBySource` json,
	`valueBySource` json,
	`dealsByStage` json,
	`valueByStage` json,
	`dealsByFOType` json,
	`conversionByFOType` json,
	`topRelationshipSources` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `deal_analytics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `follow_up_reminders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`targetType` enum('family_office','contact','deal','relationship') NOT NULL,
	`targetId` int NOT NULL,
	`targetName` varchar(255),
	`title` varchar(512) NOT NULL,
	`notes` text,
	`priority` enum('low','medium','high','urgent') DEFAULT 'medium',
	`dueDate` timestamp NOT NULL,
	`reminderTime` timestamp,
	`status` enum('pending','completed','snoozed','cancelled') DEFAULT 'pending',
	`completedAt` timestamp,
	`snoozedUntil` timestamp,
	`snoozeCount` int DEFAULT 0,
	`calendarEventId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `follow_up_reminders_id` PRIMARY KEY(`id`)
);
