CREATE TABLE `commodity_listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sellerId` int NOT NULL,
	`commodityType` enum('gold','silver','platinum','palladium','copper','iron_ore','crude_oil','natural_gas','lng','refined_products','wheat','corn','soybeans','coffee','sugar','other_mineral','other_commodity') NOT NULL,
	`goldForm` enum('bullion','dory','nuggets','sanctuary','dust','bar','coin'),
	`goldPurity` decimal(6,3),
	`goldStampAge` int,
	`oilGrade` enum('wti','brent','bonny_light','arabian_light','dubai','urals','e953','a1','v6'),
	`refinerySource` varchar(255),
	`apiGravity` decimal(5,2),
	`sulfurContent` decimal(5,3),
	`quantity` decimal(18,4) NOT NULL,
	`unit` enum('metric_tonnes','troy_ounces','kilograms','grams','barrels','gallons','cubic_meters','mmbtu','bushels','pounds','bags') NOT NULL,
	`quantityAvailableMonthly` decimal(18,4),
	`pricePerUnit` decimal(18,4),
	`currency` varchar(8) DEFAULT 'USD',
	`discountPercentage` decimal(5,2),
	`pricingBasis` varchar(128),
	`originCountry` varchar(128),
	`originRegion` varchar(255),
	`mineOrSource` varchar(255),
	`currentLocation` varchar(255),
	`deliveryLocation` varchar(255),
	`incoterms` enum('exw','fob','cif','cfr','dap','ddp','fas','fca'),
	`vesselType` varchar(128),
	`vesselCapacity` decimal(18,2),
	`tankFarm` varchar(255),
	`portDepth` varchar(64),
	`skrNumber` varchar(128),
	`skrBank` varchar(255),
	`skrVerified` boolean DEFAULT false,
	`assayReportUrl` text,
	`certificateOfOrigin` text,
	`sanctionsCleared` boolean DEFAULT false,
	`sanctionsCheckDate` timestamp,
	`exportLicenseRequired` boolean DEFAULT false,
	`exportLicenseNumber` varchar(128),
	`isConflictFree` boolean DEFAULT true,
	`status` enum('draft','active','pending_verification','reserved','sold','expired','cancelled') DEFAULT 'draft',
	`isVerified` boolean DEFAULT false,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`verificationNotes` text,
	`title` varchar(512),
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `commodity_listings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `real_estate_properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`title` varchar(512) NOT NULL,
	`address` text NOT NULL,
	`city` varchar(128),
	`state` varchar(64),
	`zipCode` varchar(20),
	`country` varchar(64) DEFAULT 'USA',
	`propertyType` enum('office','retail','industrial','multifamily','hotel','mixed_use','land','single_family','condo','warehouse','data_center','self_storage','medical','senior_living') NOT NULL,
	`totalSqFt` decimal(18,2),
	`rentableSqFt` decimal(18,2),
	`lotSize` decimal(18,2),
	`lotSizeUnit` enum('sqft','acres','sqm','hectares') DEFAULT 'sqft',
	`floors` int,
	`units` int,
	`parkingSpaces` int,
	`yearBuilt` int,
	`yearRenovated` int,
	`hasAirRights` boolean DEFAULT false,
	`airRightsSqFt` decimal(18,2),
	`zoning` varchar(64),
	`far` decimal(8,4),
	`developmentPotential` text,
	`askingPrice` decimal(18,2),
	`pricePerSqFt` decimal(12,2),
	`purchasePrice` decimal(18,2),
	`purchaseDate` timestamp,
	`grossIncome` decimal(18,2),
	`netOperatingIncome` decimal(18,2),
	`capRate` decimal(6,3),
	`occupancyRate` decimal(5,2),
	`totalTenants` int DEFAULT 0,
	`occupiedUnits` int DEFAULT 0,
	`vacantUnits` int DEFAULT 0,
	`averageRentPerSqFt` decimal(12,2),
	`weightedAverageLeaseTerm` decimal(5,2),
	`tenantRoll` json,
	`comparables` json,
	`aiUnderwritingScore` decimal(5,2),
	`aiUnderwritingNotes` text,
	`aiUnderwritingCriteria` json,
	`lastUnderwritingDate` timestamp,
	`status` enum('draft','off_market','coming_soon','active','under_contract','due_diligence','pending','sold','withdrawn') DEFAULT 'draft',
	`listingType` enum('sale','lease','sale_leaseback','joint_venture') DEFAULT 'sale',
	`isOffMarket` boolean DEFAULT true,
	`photos` json,
	`floorPlans` json,
	`virtualTourUrl` text,
	`offeringMemorandumId` int,
	`rentRollDocumentId` int,
	`financialStatementsId` int,
	`isVerified` boolean DEFAULT false,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `real_estate_properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transaction_criteria` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`criteriaType` enum('buy','sell','invest','lend') NOT NULL,
	`assetClass` enum('gold','oil_gas','minerals','commodities','real_estate','private_equity','venture_capital','debt','infrastructure','other') NOT NULL,
	`commodityTypes` json,
	`minPurity` decimal(6,3),
	`preferredOrigins` json,
	`preferredDeliveryLocations` json,
	`preferredBanks` json,
	`requiresSKR` boolean DEFAULT false,
	`propertyTypes` json,
	`preferredMarkets` json,
	`minCapRate` decimal(6,3),
	`maxCapRate` decimal(6,3),
	`minOccupancy` decimal(5,2),
	`minQuantity` decimal(18,4),
	`maxQuantity` decimal(18,4),
	`quantityUnit` varchar(32),
	`frequencyPerMonth` int,
	`minPrice` decimal(18,4),
	`maxPrice` decimal(18,4),
	`maxDiscountFromSpot` decimal(5,2),
	`requiresVerifiedSeller` boolean DEFAULT true,
	`requiresComplianceCleared` boolean DEFAULT true,
	`requiresProofOfFunds` boolean DEFAULT false,
	`requiresProofOfProduct` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`additionalRequirements` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `transaction_criteria_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transaction_matches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`buyerCriteriaId` int NOT NULL,
	`sellerListingId` int NOT NULL,
	`listingType` enum('commodity','real_estate') NOT NULL,
	`buyerId` int NOT NULL,
	`sellerId` int NOT NULL,
	`matchScore` decimal(5,2) NOT NULL,
	`matchFactors` json,
	`status` enum('pending','buyer_interested','seller_interested','mutual_interest','negotiating','due_diligence','under_contract','completed','declined') DEFAULT 'pending',
	`proposedPrice` decimal(18,4),
	`proposedQuantity` decimal(18,4),
	`counterOffers` json,
	`dealRoomId` int,
	`buyerVerified` boolean DEFAULT false,
	`sellerVerified` boolean DEFAULT false,
	`proofOfFundsVerified` boolean DEFAULT false,
	`proofOfProductVerified` boolean DEFAULT false,
	`complianceCleared` boolean DEFAULT false,
	`complianceCheckId` int,
	`finalPrice` decimal(18,4),
	`finalQuantity` decimal(18,4),
	`closedAt` timestamp,
	`introducedBy` int,
	`commissionPercentage` decimal(5,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `transaction_matches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `verification_proofs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`proofType` enum('proof_of_funds','proof_of_product','skr','bank_statement','assay_report') NOT NULL,
	`bankName` varchar(255),
	`accountType` varchar(64),
	`availableFunds` decimal(18,2),
	`currency` varchar(8) DEFAULT 'USD',
	`productType` varchar(128),
	`quantity` decimal(18,4),
	`unit` varchar(32),
	`location` varchar(255),
	`documentUrl` text,
	`documentKey` varchar(512),
	`status` enum('pending','verified','rejected','expired') DEFAULT 'pending',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`verificationNotes` text,
	`expiresAt` timestamp,
	`isPublic` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `verification_proofs_id` PRIMARY KEY(`id`)
);
