CREATE TABLE `audit_logs` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userEmail` varchar(320),
	`userRole` varchar(64),
	`ipAddress` varchar(45),
	`userAgent` text,
	`action` varchar(128) NOT NULL,
	`actionCategory` enum('auth','user','spv','lp','commitment','capital_call','deal','deal_room','document','compliance','payout','admin','system') NOT NULL,
	`entityType` varchar(64),
	`entityId` int,
	`entityName` varchar(255),
	`previousState` json,
	`newState` json,
	`metadata` json,
	`riskLevel` enum('low','medium','high','critical') DEFAULT 'low',
	`complianceRelevant` boolean DEFAULT false,
	`requiresReview` boolean DEFAULT false,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`checksum` varchar(64),
	`previousLogId` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cap_table_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`spvId` int NOT NULL,
	`holderId` int NOT NULL,
	`holderType` enum('lp','gp','carry_holder','other') NOT NULL,
	`units` decimal(18,6),
	`ownershipPercentage` decimal(8,5) NOT NULL,
	`shareClass` varchar(64) DEFAULT 'Common',
	`votingRights` boolean DEFAULT true,
	`capitalContributed` decimal(18,2) DEFAULT '0.00',
	`currentValue` decimal(18,2),
	`issuedAt` timestamp NOT NULL,
	`vestedAt` timestamp,
	`status` enum('active','transferred','redeemed','cancelled') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cap_table_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `capital_call_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`capitalCallId` int NOT NULL,
	`commitmentId` int NOT NULL,
	`lpProfileId` int NOT NULL,
	`amountDue` decimal(18,2) NOT NULL,
	`amountPaid` decimal(18,2) DEFAULT '0.00',
	`status` enum('pending','partial','paid','overdue','defaulted') DEFAULT 'pending',
	`paidAt` timestamp,
	`paymentMethod` varchar(64),
	`paymentReference` varchar(255),
	`confirmedBy` int,
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `capital_call_responses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `capital_calls` (
	`id` int AUTO_INCREMENT NOT NULL,
	`spvId` int NOT NULL,
	`callNumber` int NOT NULL,
	`callAmount` decimal(18,2) NOT NULL,
	`callPercentage` decimal(5,2),
	`purpose` text,
	`status` enum('draft','sent','partial','complete','cancelled') DEFAULT 'draft',
	`noticeDate` timestamp,
	`dueDate` timestamp NOT NULL,
	`totalCalled` decimal(18,2) DEFAULT '0.00',
	`totalReceived` decimal(18,2) DEFAULT '0.00',
	`noticeDocumentId` int,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `capital_calls_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `capital_commitments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`spvId` int NOT NULL,
	`lpProfileId` int NOT NULL,
	`userId` int NOT NULL,
	`commitmentAmount` decimal(18,2) NOT NULL,
	`currency` varchar(8) DEFAULT 'USD',
	`ownershipPercentage` decimal(8,5),
	`status` enum('pending','signed','funded','partially_funded','cancelled','transferred') DEFAULT 'pending',
	`subscriptionDate` timestamp,
	`subscriptionDocumentId` int,
	`signedAt` timestamp,
	`amountCalled` decimal(18,2) DEFAULT '0.00',
	`amountFunded` decimal(18,2) DEFAULT '0.00',
	`unfundedCommitment` decimal(18,2),
	`totalDistributions` decimal(18,2) DEFAULT '0.00',
	`returnOfCapital` decimal(18,2) DEFAULT '0.00',
	`profits` decimal(18,2) DEFAULT '0.00',
	`hasSideLetter` boolean DEFAULT false,
	`sideLetterTerms` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `capital_commitments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compliance_checklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` enum('spv','lp','deal','user') NOT NULL,
	`entityId` int NOT NULL,
	`checklistType` enum('kyc','aml','accreditation','sanctions','pep','adverse_media','deal_compliance','regulatory_filing','annual_review') NOT NULL,
	`status` enum('pending','in_progress','passed','failed','expired') DEFAULT 'pending',
	`items` json,
	`passedItems` int DEFAULT 0,
	`failedItems` int DEFAULT 0,
	`totalItems` int DEFAULT 0,
	`assignedTo` int,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`dueDate` timestamp,
	`completedAt` timestamp,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `compliance_checklists_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lp_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`lpType` enum('individual','family_office','institutional','ria','endowment','pension','sovereign_wealth','corporate','other') NOT NULL,
	`accreditationStatus` enum('pending','accredited','qualified_purchaser','qualified_client','not_accredited') DEFAULT 'pending',
	`accreditationMethod` enum('income','net_worth','professional','entity','other'),
	`accreditationVerifiedAt` timestamp,
	`accreditationExpiresAt` timestamp,
	`accreditationDocumentId` int,
	`investableAssets` decimal(18,2),
	`annualIncome` decimal(18,2),
	`investmentExperience` enum('none','limited','moderate','extensive','professional') DEFAULT 'limited',
	`riskTolerance` enum('conservative','moderate','aggressive') DEFAULT 'moderate',
	`preferredAssetClasses` json,
	`preferredIndustries` json,
	`preferredGeographies` json,
	`minimumCheckSize` decimal(18,2),
	`maximumCheckSize` decimal(18,2),
	`kycStatus` enum('pending','in_review','approved','rejected') DEFAULT 'pending',
	`kycVerifiedAt` timestamp,
	`amlCleared` boolean DEFAULT false,
	`amlClearedAt` timestamp,
	`pepStatus` boolean DEFAULT false,
	`bankName` varchar(255),
	`bankAccountLast4` varchar(4),
	`wireInstructionsId` int,
	`totalInvested` decimal(18,2) DEFAULT '0.00',
	`totalDistributions` decimal(18,2) DEFAULT '0.00',
	`activeInvestments` int DEFAULT 0,
	`reinvestmentRate` decimal(5,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lp_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `spvs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`legalName` varchar(512),
	`description` text,
	`entityType` enum('llc','lp','gp','corp','series_llc','trust','offshore') NOT NULL DEFAULT 'llc',
	`jurisdiction` varchar(128) NOT NULL,
	`stateOfFormation` varchar(64),
	`einNumber` varchar(32),
	`formationDate` timestamp,
	`investmentPurpose` text,
	`targetAssetClass` enum('real_estate','private_equity','venture_capital','hedge_fund','commodities','infrastructure','debt','mixed','other'),
	`targetIndustry` varchar(128),
	`targetRaise` decimal(18,2),
	`minimumInvestment` decimal(18,2),
	`maximumInvestment` decimal(18,2),
	`totalCommitted` decimal(18,2) DEFAULT '0.00',
	`totalCalled` decimal(18,2) DEFAULT '0.00',
	`totalDistributed` decimal(18,2) DEFAULT '0.00',
	`currency` varchar(8) DEFAULT 'USD',
	`managementFee` decimal(5,2),
	`carriedInterest` decimal(5,2),
	`preferredReturn` decimal(5,2),
	`status` enum('draft','formation','fundraising','closed','active','liquidating','dissolved') DEFAULT 'draft',
	`sponsorId` int NOT NULL,
	`managerId` int,
	`adminId` int,
	`dealRoomId` int,
	`complianceStatus` enum('pending','approved','flagged','blocked') DEFAULT 'pending',
	`regulatoryFilings` json,
	`operatingAgreementId` int,
	`ppmDocumentId` int,
	`subscriptionAgreementId` int,
	`fundingDeadline` timestamp,
	`investmentPeriodEnd` timestamp,
	`termEndDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `spvs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wire_instructions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`ownerType` enum('user','spv','lp') NOT NULL,
	`bankName` varchar(255) NOT NULL,
	`bankAddress` text,
	`routingNumber` varchar(32),
	`accountNumber` varchar(64),
	`accountName` varchar(255),
	`swiftCode` varchar(16),
	`iban` varchar(64),
	`intermediaryBankName` varchar(255),
	`intermediarySwiftCode` varchar(16),
	`reference` varchar(255),
	`specialInstructions` text,
	`isVerified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`verifiedBy` int,
	`isPrimary` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wire_instructions_id` PRIMARY KEY(`id`)
);
